### ISSUE TITLE
path does not exist

### ISSUE THREAD

**Issue by Shadow322** [retrogamecorps/GKD-Pixel-MinUI-Addons#2]
I have mounted the stock sd card and the modded fw card and this path does not exist do i make it?

"if you need to add your own, they should go in the /media/data/local/home/.pcsx4all/bios folder on your card's Linux partition."

**Comment by retrogamecorps** [comment]
This path exists on the Linux partition, you won't see it if you are plugging the card into a Windows PC or Mac.  The partition you see on Windows and Mac is different.  If you are using the stock SD card, it will already have those BIOS files in the Linux partition, you can check it by using the "Files" app within the Tool section of MinUI, or the Commander app within the stock UIX OS to navigate to that location.  You can also just boot a PS1 game and if it boots, you have the BIOS loaded already.

**Comment by Shadow322** [comment]
> This path exists on the Linux partition, you won't see it if you are plugging the card into a Windows PC or Mac. The partition you see on Windows and Mac is different. If you are using the stock SD card, it will already have those BIOS files in the Linux partition, you can check it by using the "Files" app within the Tool section of MinUI, or the Commander app within the stock UIX OS to navigate to that location. You can also just boot a PS1 game and if it boots, you have the BIOS loaded already.

I am mounting it on linux

**Comment by Shadow322** [comment]
and when i put a psx game under PS-ALT it just blinks and does nothing im using this as base image https://github.com/game-de-it/GKDpixel_StockOS_v2/releases/tag/GKDpixel_StockOS_v2.1_update and i even looked at the stock sd card the path isnt there

**Comment by retrogamecorps** [comment]
Ah okay, then if you are using their stock software image then the BIOS have been removed.  I assumed you were using the original stock card that came with the device.  I think you can just launch PCSX4all on its own and it should create those folders for you when the boots, but if it doesn't then yes you'll need to make the .pcsx4all/bios folder and put the BIOS within, much like how we had to back in the OpenDingux days.

**Comment by Shadow322** [comment]
ok this time around i followed your video guide but this time didnt copy the stock files to a stock folder left them where they was and psx4all works so its something in the accessible area of the sd card that was removed
